"use client";
import Image from "next/image";
import { Heart, LockKeyhole, Play, RotateCcw, Sparkles } from "lucide-react";
import { useState } from "react";

export default function GalleryPage(){const[open,setOpen]=useState(false);return <main className={`customer-gallery ${open?"revealed":""}`}>
 {!open?<section className="gift-reveal"><div className="gallery-lock"><LockKeyhole size={14}/>A private Mathaka memory</div><div className="gift-scene" aria-hidden="true"><span className="confetti c1"/><span className="confetti c2"/><span className="confetti c3"/><div className="gift-lid"><i/></div><div className="gift-box"><i/></div><div className="gift-shadow"/></div><span className="eyebrow">A little something for you</span><h1>Isuri, your surprise<br/>is ready to unwrap.</h1><p>Sent across the miles with love from Nadeesha.</p><button onClick={()=>setOpen(true)}><Sparkles size={18}/>Tap to unwrap</button><small>Best enjoyed with sound on and a happy heart.</small></section>:
 <section className="memory-page"><header><div className="gallery-wordmark"><Heart/>mathaka</div><button onClick={()=>setOpen(false)}><RotateCcw size={15}/>Replay</button></header><div className="memory-intro"><span className="eyebrow">9 August 2026 · Colombo</span><h1>Happy birthday,<br/><em>Isuri.</em></h1><p>“Even from far away, I wanted you to feel how loved you are today. May this next year bring you brave dreams, easy laughter, and so many beautiful memories.”</p><strong>With all my love, Nadeesha</strong></div><section className="memory-mosaic"><figure className="memory-main"><Image src="/assets/celebration-table.png" alt="Birthday cake, flowers and wrapped gifts arranged for Isuri" fill priority sizes="(max-width: 700px) 100vw, 65vw"/><figcaption>The surprise, just before the doorbell rang.</figcaption></figure><figure className="memory-crop crop-one"><Image src="/assets/celebration-table.png" alt="Marigold and blush birthday flowers" fill sizes="(max-width: 700px) 50vw, 30vw"/></figure><figure className="memory-video"><Image src="/assets/celebration-table.png" alt="Preview of Isuri's celebration video" fill sizes="(max-width: 700px) 100vw, 40vw"/><button aria-label="Play celebration video"><Play fill="currentColor"/></button><span>00:28 · The moment</span></figure><blockquote>“Some distances are measured in miles. Others disappear with one thoughtful surprise.”</blockquote></section><footer><span>Thoughtfully brought to life by</span><strong>Mathaka</strong><p>From a message to a memory.</p></footer></section>}
 </main>}
