import {NextResponse} from "next/server";
import {requirePermission} from "@/lib/server/auth";
import {getDatabase} from "@/lib/server/database";
import {catalogItemSchema,inventoryAdjustmentSchema,inventoryItemSchema,studioSectionSchema,taskTemplateSchema} from "@/lib/server/validation";

export async function GET(request:Request){
 const staff=await requirePermission("studio.read");if(!staff)return NextResponse.json({error:"Unauthorized"},{status:401});
 const section=studioSectionSchema.safeParse(new URL(request.url).searchParams.get("section"));if(!section.success)return NextResponse.json({error:"Invalid studio section"},{status:400});
 const sql=getDatabase();let data:readonly unknown[]=[];let summary:Record<string,number>|undefined;
 if(section.data==="customers")data=await sql`select c.id::text,c.name,c.whatsapp as phone,c.country,c.created_at,count(distinct i.id)::int as celebration_count,coalesce(sum(i.total),0) as lifetime_value,coalesce(sum(i.total-coalesce(i.amount_paid,0)),0) as outstanding from public.customers c left join public.invoices i on i.customer_id=c.id group by c.id order by c.updated_at desc nulls last,c.id desc limit 500`;
 if(section.data==="catalogue")data=await sql`select id::text,name,category,description,unit_price,cost_price,active,created_at,updated_at from public.studio_catalog_items where organization_id=${staff.organizationId}::uuid order by active desc,name`;
 if(section.data==="calendar")data=await sql`select i.id::text,coalesce(d.title,i.invoice_number) title,c.name customer,coalesce(r.name,'Recipient pending') recipient,j.delivery_at,coalesce(j.journey_status,i.order_status,'details') status,z.name district from public.invoices i join public.customers c on c.id=i.customer_id left join public.recipients r on r.id=i.recipient_id left join public.celebration_journeys j on j.invoice_id=i.id left join public.important_dates d on d.customer_id=i.customer_id and d.recipient_id is not distinct from i.recipient_id left join public.delivery_zones z on z.id=i.delivery_zone_id where coalesce(j.delivery_at,i.created_at)>=now()-interval '30 days' order by coalesce(j.delivery_at,i.created_at) limit 500`;
 if(section.data==="alerts")data=await sql`select * from (select 'payment_due' kind,i.id::text entity_id,coalesce(r.name,c.name) title,concat('LKR ',greatest(i.total-coalesce(i.amount_paid,0),0),' remaining') detail,j.delivery_at due_at from public.invoices i join public.customers c on c.id=i.customer_id left join public.recipients r on r.id=i.recipient_id left join public.celebration_journeys j on j.invoice_id=i.id where i.total>coalesce(i.amount_paid,0) union all select 'low_stock',s.id::text,s.name,concat(s.quantity_on_hand,' ',s.unit,' remaining'),null from public.studio_inventory_items s where s.organization_id=${staff.organizationId}::uuid and s.active and s.quantity_on_hand<=s.reorder_level) alerts order by due_at nulls last limit 200`;
 if(section.data==="reports"){data=await sql`select date_trunc('month',i.created_at)::date period,count(*)::int celebrations,coalesce(sum(i.total),0) invoiced,coalesce(sum(i.amount_paid),0) collected,coalesce(sum(i.total_cost),0) costs,coalesce(sum(i.amount_paid-i.total_cost),0) cash_profit from public.invoices i where i.created_at>=date_trunc('month',now())-interval '11 months' group by 1 order by 1`;const [s]=await sql`select count(*)::int celebrations,coalesce(sum(total),0) invoiced,coalesce(sum(amount_paid),0) collected,coalesce(sum(total_cost),0) costs from public.invoices`;summary={celebrations:Number(s.celebrations),invoiced:Number(s.invoiced),collected:Number(s.collected),costs:Number(s.costs)};}
 if(section.data==="inventory")data=await sql`select s.id::text,s.catalog_item_id::text,s.name,s.sku,s.unit,s.quantity_on_hand,s.reorder_level,s.active,c.name catalog_name,s.updated_at from public.studio_inventory_items s left join public.studio_catalog_items c on c.id=s.catalog_item_id where s.organization_id=${staff.organizationId}::uuid order by s.active desc,s.name`;
 if(section.data==="templates")data=await sql`select id::text,name,occasion,active,steps,created_at,updated_at from public.studio_task_templates where organization_id=${staff.organizationId}::uuid order by active desc,name`;
 return NextResponse.json({section:section.data,data,summary});
}

export async function POST(request:Request){
 const staff=await requirePermission("celebrations.write");if(!staff)return NextResponse.json({error:"Forbidden"},{status:403});const body=await request.json().catch(()=>null) as Record<string,unknown>|null,section=studioSectionSchema.safeParse(body?.section);if(!body||!section.success||!["catalogue","inventory","templates"].includes(section.data))return NextResponse.json({error:"Invalid studio mutation"},{status:400});const sql=getDatabase();
 if(section.data==="catalogue"){const p=catalogItemSchema.safeParse(body.data);if(!p.success)return NextResponse.json({error:"Invalid catalogue item",details:p.error.flatten()},{status:400});const [item]=await sql`insert into public.studio_catalog_items(organization_id,name,category,description,unit_price,cost_price,active,created_by) values(${staff.organizationId}::uuid,${p.data.name},${p.data.category},${p.data.description??null},${p.data.unitPrice},${p.data.costPrice},${p.data.active},${staff.subject}::uuid) returning *`;return NextResponse.json({section:section.data,item},{status:201});}
 if(section.data==="templates"){const p=taskTemplateSchema.safeParse(body.data);if(!p.success)return NextResponse.json({error:"Invalid task template",details:p.error.flatten()},{status:400});const [item]=await sql`insert into public.studio_task_templates(organization_id,name,occasion,active,steps,created_by) values(${staff.organizationId}::uuid,${p.data.name},${p.data.occasion??null},${p.data.active},${sql.json(p.data.steps)},${staff.subject}::uuid) returning *`;return NextResponse.json({section:section.data,item},{status:201});}
 if(body.action==="adjust"){const p=inventoryAdjustmentSchema.safeParse(body.data);if(!p.success)return NextResponse.json({error:"Invalid stock adjustment",details:p.error.flatten()},{status:400});const item=await sql.begin(async tx=>{const rows=await tx`update public.studio_inventory_items set quantity_on_hand=quantity_on_hand+${p.data.quantityDelta},updated_at=now() where id=${p.data.inventoryItemId}::uuid and organization_id=${staff.organizationId}::uuid returning *`;if(!rows[0])return null;await tx`insert into public.studio_inventory_adjustments(inventory_item_id,quantity_delta,reason,reference,created_by) values(${p.data.inventoryItemId}::uuid,${p.data.quantityDelta},${p.data.reason},${p.data.reference??null},${staff.subject}::uuid)`;return rows[0]});return item?NextResponse.json({section:section.data,item}):NextResponse.json({error:"Inventory item not found"},{status:404});}
 const p=inventoryItemSchema.safeParse(body.data);if(!p.success)return NextResponse.json({error:"Invalid inventory item",details:p.error.flatten()},{status:400});const [item]=await sql`insert into public.studio_inventory_items(organization_id,catalog_item_id,name,sku,unit,quantity_on_hand,reorder_level,active,created_by) values(${staff.organizationId}::uuid,${p.data.catalogItemId??null},${p.data.name},${p.data.sku??null},${p.data.unit},${p.data.quantityOnHand},${p.data.reorderLevel},${p.data.active},${staff.subject}::uuid) returning *`;return NextResponse.json({section:section.data,item},{status:201});
}

export async function PATCH(request:Request){
 const staff=await requirePermission("celebrations.write");if(!staff)return NextResponse.json({error:"Forbidden"},{status:403});const body=await request.json().catch(()=>null) as Record<string,unknown>|null,section=studioSectionSchema.safeParse(body?.section),id=typeof body?.id==='string'?body.id:'';if(!body||!section.success||!id)return NextResponse.json({error:"Invalid studio mutation"},{status:400});const sql=getDatabase();
 if(section.data==="catalogue"){const p=catalogItemSchema.safeParse(body.data);if(!p.success)return NextResponse.json({error:"Invalid catalogue item",details:p.error.flatten()},{status:400});const [item]=await sql`update public.studio_catalog_items set name=${p.data.name},category=${p.data.category},description=${p.data.description??null},unit_price=${p.data.unitPrice},cost_price=${p.data.costPrice},active=${p.data.active},updated_at=now() where id=${id}::uuid and organization_id=${staff.organizationId}::uuid returning *`;return NextResponse.json({section:section.data,item});}
 if(section.data==="inventory"){const p=inventoryItemSchema.safeParse(body.data);if(!p.success)return NextResponse.json({error:"Invalid inventory item",details:p.error.flatten()},{status:400});const [item]=await sql`update public.studio_inventory_items set catalog_item_id=${p.data.catalogItemId??null},name=${p.data.name},sku=${p.data.sku??null},unit=${p.data.unit},quantity_on_hand=${p.data.quantityOnHand},reorder_level=${p.data.reorderLevel},active=${p.data.active},updated_at=now() where id=${id}::uuid and organization_id=${staff.organizationId}::uuid returning *`;return NextResponse.json({section:section.data,item});}
 if(section.data==="templates"){const p=taskTemplateSchema.safeParse(body.data);if(!p.success)return NextResponse.json({error:"Invalid task template",details:p.error.flatten()},{status:400});const [item]=await sql`update public.studio_task_templates set name=${p.data.name},occasion=${p.data.occasion??null},active=${p.data.active},steps=${sql.json(p.data.steps)},updated_at=now() where id=${id}::uuid and organization_id=${staff.organizationId}::uuid returning *`;return NextResponse.json({section:section.data,item});}
 return NextResponse.json({error:"This section is read-only"},{status:405});
}
