"use client";

import Link from "next/link";
import { use, useCallback, useEffect, useState } from "react";
import { AlertCircle, ArrowLeft, BadgeCheck, Ban, Check, Download, ExternalLink, LoaderCircle, Printer, RefreshCw, Send, WalletCards } from "lucide-react";
import { AppShell } from "@/components/app-shell";
import { formatLkr } from "@/lib/demo-data";

type Line = { id?: string; description: string; quantity: number; unitPrice: number; total: number };
type Activity = { id?: string; action: string; detail?: string; createdAt: string; actor?: string };
type Payment = { id: string; amount: number; method?: string; reference?: string; paidAt?: string; verified?: boolean };
type DocumentDetail = { id: string; number: string; type: string; status: string; issueDate: string; dueDate?: string; customerName: string; customerEmail?: string; customerPhone?: string; customerAddress?: string; business?: { name?: string; address?: string; phone?: string; email?: string; taxId?: string; bankInstructions?: string }; lineItems: Line[]; subtotal: number; discount: number; tax: number; total: number; paid: number; balance: number; terms?: string; footer?: string; notes?: string; payments: Payment[]; activity: Activity[] };

export default function BillingDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = use(params); const [document, setDocument] = useState<DocumentDetail | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [busy, setBusy] = useState(""); const [notice, setNotice] = useState(""); const [shareUrl, setShareUrl] = useState("");
  const load = useCallback(async () => { setLoading(true); setError(""); try { const response = await fetch(`/api/invoices/${id}`, { cache: "no-store" }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error || "This document could not be opened."); const wrapped = payload.invoice || payload; const raw = wrapped.document || wrapped; const customer = raw.customer_snapshot || {}; const business = raw.business_snapshot || {}; setDocument({ id: String(raw.id), number: String(raw.document_number || "Draft"), type: String(raw.document_type || "invoice"), status: String(raw.status || "draft"), issueDate: String(raw.issue_date || raw.created_at || ""), dueDate: raw.due_date, customerName: String(customer.name || "Customer"), customerPhone: customer.phone, customerAddress: customer.address, business: { name: business.name, address: business.address, phone: business.phone, email: business.email, taxId: business.tax_identifier, bankInstructions: raw.payment_instructions_snapshot }, lineItems: (wrapped.items || []).map((line: Record<string, unknown>) => ({ id: line.id ? String(line.id) : undefined, description: String(line.description || "Item"), quantity: Number(line.quantity || 1), unitPrice: Number(line.unit_price || 0), total: Number(line.line_total ?? Number(line.quantity || 1) * Number(line.unit_price || 0)) })), subtotal: Number(raw.subtotal || 0), discount: Number(raw.discount || 0), tax: Number(raw.tax_amount || 0), total: Number(raw.total || 0), paid: Number(raw.paid || 0), balance: Number(raw.total || 0) - Number(raw.paid || 0), terms: raw.terms_snapshot, footer: raw.footer_text, payments: raw.payments || [], activity: raw.activity || [] }); } catch (caught) { setError(caught instanceof Error ? caught.message : "This document could not be opened."); } finally { setLoading(false); } }, [id]);
  useEffect(() => { const timer = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timer); }, [load]);
  async function action(name: "issue" | "void" | "share") { setBusy(name); setError(""); try { const suffix = name === "share" ? "share-links" : name; const body = name === "share" ? { expiresInHours: 168 } : name === "void" ? { reason: "Voided by studio staff" } : {}; const response = await fetch(`/api/invoices/${id}/${suffix}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error || `The document could not be ${name === "issue" ? "issued" : name === "void" ? "voided" : "shared"}.`); if (payload.url) { setShareUrl(payload.url); await navigator.clipboard.writeText(payload.url); } setNotice(name === "share" ? "Secure customer link copied. It is ready to preview below." : name === "issue" ? "Document issued." : "Document voided."); void load(); } catch (caught) { setError(caught instanceof Error ? caught.message : "That action could not be completed."); } finally { setBusy(""); } }
  if (loading) return <AppShell><div className="detail-page detail-state"><LoaderCircle className="spin"/><h1>Unfolding the invoice…</h1><p>Loading the saved document snapshot, payments and activity.</p></div></AppShell>;
  if (!document || error && !document) return <AppShell><div className="detail-page detail-state error"><AlertCircle/><h1>This document stayed in the drawer.</h1><p>{error || "It may have been removed or you may not have access."}</p><button className="primary-button" onClick={() => void load()}><RefreshCw size={16}/>Try again</button><Link className="secondary-button" href="/billing">Back to billing</Link></div></AppShell>;
  const editable = document.status === "draft";
  return <AppShell><div className="detail-page billing-detail"><div className="detail-top"><Link className="back-link" href="/billing"><ArrowLeft size={16}/>Billing</Link><div className="detail-actions"><button className="secondary-button" onClick={() => window.print()}><Printer size={16}/>Print</button><button className="secondary-button" onClick={() => window.print()}><Download size={16}/>Save PDF</button><button className="primary-button" onClick={() => void action("share")} disabled={busy === "share" || document.status === "draft"}><Send size={16}/>{busy === "share" ? "Preparing…" : "Share"}</button></div></div>
    {error && <div className="operational-notice error"><AlertCircle size={17}/>{error}</div>}{notice && <div className="operational-notice success"><Check size={17}/>{notice}</div>}
    <header className="document-heading"><div><span className="eyebrow">{pretty(document.type)}</span><h1>{document.number}</h1><p>Issued {shortDate(document.issueDate)}{document.dueDate ? ` · due ${shortDate(document.dueDate)}` : ""}</p></div><span className={`billing-status ${document.status}`}>{pretty(document.status)}</span></header>
    <div className="document-workspace"><article className="invoice-paper"><header><div className="invoice-brand"><span className="brand-mark"><span/></span><div><strong>{document.business?.name || "Mathaka"}</strong><small>Celebration studio</small></div></div><div className="invoice-title"><small>{pretty(document.type)}</small><strong>{document.number}</strong></div></header><section className="invoice-addresses"><div><small>From the studio</small><strong>{document.business?.name || "Mathaka Celebration Studio"}</strong><p>{document.business?.address || "Sri Lanka"}<br/>{document.business?.phone || ""}<br/>{document.business?.email || ""}</p></div><div><small>Prepared for</small><strong>{document.customerName}</strong><p>{document.customerAddress}<br/>{document.customerPhone}<br/>{document.customerEmail}</p></div></section><table><thead><tr><th>Description</th><th>Qty</th><th>Rate</th><th>Amount</th></tr></thead><tbody>{document.lineItems.map((line, index) => <tr key={line.id || index}><td>{line.description}</td><td>{line.quantity}</td><td>{formatLkr(line.unitPrice)}</td><td>{formatLkr(line.total)}</td></tr>)}</tbody></table><section className="invoice-totals"><div>{document.notes && <><small>Note</small><p>{document.notes}</p></>}</div><dl><div><dt>Subtotal</dt><dd>{formatLkr(document.subtotal)}</dd></div>{document.discount > 0 && <div><dt>Discount</dt><dd>−{formatLkr(document.discount)}</dd></div>}{document.tax > 0 && <div><dt>Tax</dt><dd>{formatLkr(document.tax)}</dd></div>}<div className="grand"><dt>Total</dt><dd>{formatLkr(document.total)}</dd></div><div><dt>Paid</dt><dd>{formatLkr(document.paid)}</dd></div><div className="balance"><dt>Balance due</dt><dd>{formatLkr(document.balance)}</dd></div></dl></section>{document.terms && <section className="invoice-terms"><small>Terms & conditions</small><p>{document.terms}</p></section>}<footer>{document.footer || document.business?.bankInstructions || "Thank you for celebrating with Mathaka."}</footer></article>
      <aside className="document-rail"><section><span className="eyebrow">Document actions</span><h2>Keep the paper trail clear.</h2>{editable ? <button className="primary-button" onClick={() => void action("issue")} disabled={Boolean(busy)}><BadgeCheck size={16}/>Issue document</button> : <button className="secondary-button" onClick={() => void action("void")} disabled={Boolean(busy) || ["paid","void","refunded"].includes(document.status)}><Ban size={16}/>Void document</button>}{shareUrl ? <a className="text-link secure-preview" href={shareUrl} target="_blank" rel="noreferrer">Preview secure customer link <ExternalLink size={13}/></a> : <p className="rail-empty">Use Share to create a secure customer link. Internal document IDs are never exposed.</p>}</section><section><span className="eyebrow">Payments</span><h2>{formatLkr(document.paid)} collected</h2>{document.payments.length ? <div className="document-payments">{document.payments.map((payment) => <div key={payment.id}><WalletCards size={17}/><span><strong>{formatLkr(payment.amount)}</strong><small>{payment.method || "Payment"} · {shortDate(payment.paidAt)}</small></span>{payment.verified && <BadgeCheck aria-label="Verified"/>}</div>)}</div> : <p className="rail-empty">No payments are attached to this document yet.</p>}</section><section><span className="eyebrow">Activity</span><div className="document-activity">{document.activity.length ? document.activity.map((entry, index) => <div key={entry.id || index}><i/><p><strong>{entry.action}</strong><small>{entry.detail || entry.actor || "Studio activity"} · {shortDate(entry.createdAt)}</small></p></div>) : <p className="rail-empty">Activity appears after the document is issued or shared.</p>}</div></section></aside></div>
  </div></AppShell>;
}
function pretty(value: string) { return value.replaceAll("_", " ").replace(/\b\w/g, (letter) => letter.toUpperCase()); }
function shortDate(value?: string) { if (!value) return "—"; const date = new Date(value); return Number.isNaN(date.valueOf()) ? value : new Intl.DateTimeFormat("en-LK", { day: "2-digit", month: "short", year: "numeric" }).format(date); }
