"use client";

import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";
import Link from "next/link";
import { AlertCircle, ArrowLeft, Check, LoaderCircle, Plus, X } from "lucide-react";
import { AppShell } from "@/components/app-shell";

const initial = { sender: "", senderPhone: "", senderCountry: "", recipient: "", recipientPhone: "", occasion: "", deliveryDate: "", deliveryTime: "", address: "", district: "", mode: "Self", specialRequest: "", total: "", items: [""] };

export default function NewCelebrationPage() {
  const router = useRouter();
  const [busy,setBusy]=useState(false); const [error,setError]=useState(""); const [form,setForm]=useState(initial);
  const update=(key:string,value:unknown)=>setForm((current)=>({...current,[key]:value}));
  async function submit(event:FormEvent){event.preventDefault();setBusy(true);setError("");try{const response=await fetch("/api/orders",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...form,senderCountry:form.senderCountry||null,recipientPhone:form.recipientPhone||null,deliveryDate:form.deliveryDate||null,deliveryTime:form.deliveryTime||null,address:form.address||null,district:form.district||null,specialRequest:form.specialRequest||null,total:Number(form.total||0),items:form.items.filter((item)=>item.trim())})});const payload=await response.json().catch(()=>null) as {orderId?:number;error?:string}|null;if(!response.ok||!payload?.orderId)throw new Error(payload?.error||"The celebration could not be created.");router.push(`/celebrations/${payload.orderId}`)}catch(caught){setError(caught instanceof Error?caught.message:"The celebration could not be created.")}finally{setBusy(false)}}
  return <AppShell><div className="page new-celebration-page"><Link href="/celebrations" className="back-link"><ArrowLeft size={16}/>Celebrations</Link><header className="page-header"><div><span className="eyebrow">New studio work card</span><h1>Create a celebration.</h1><p>For phone calls, walk-ins, and orders that did not begin in WhatsApp.</p></div></header>{error&&<div className="operational-notice error" role="alert"><AlertCircle size={18}/><span>{error}</span></div>}<form className="manual-celebration-form paper-panel" onSubmit={(event)=>void submit(event)}><section><h2>People</h2><div className="editor-grid"><Field label="Sender" value={form.sender} set={(value)=>update("sender",value)} required/><Field label="Sender phone" value={form.senderPhone} set={(value)=>update("senderPhone",value)} required type="tel"/><Field label="Sender country" value={form.senderCountry} set={(value)=>update("senderCountry",value)}/><Field label="Recipient" value={form.recipient} set={(value)=>update("recipient",value)} required/><Field label="Recipient phone" value={form.recipientPhone} set={(value)=>update("recipientPhone",value)} type="tel"/></div></section><section><h2>Celebration and delivery</h2><div className="editor-grid"><Field label="Occasion" value={form.occasion} set={(value)=>update("occasion",value)} required/><Field label="Delivery date" value={form.deliveryDate} set={(value)=>update("deliveryDate",value)} type="date"/><Field label="Delivery time" value={form.deliveryTime} set={(value)=>update("deliveryTime",value)} type="time"/><Field label="District" value={form.district} set={(value)=>update("district",value)}/><Field label="Address" value={form.address} set={(value)=>update("address",value)} wide/><label>Fulfilment<select value={form.mode} onChange={(event)=>update("mode",event.target.value)}><option>Self</option><option>Partner</option><option>Hybrid</option></select></label><Field label="Agreed total (LKR)" value={form.total} set={(value)=>update("total",value)} type="number"/><Field label="Special request" value={form.specialRequest} set={(value)=>update("specialRequest",value)} wide/></div></section><section><h2>Requested items</h2><div className="editor-items">{form.items.map((item,index)=><div key={index}><input value={item} onChange={(event)=>update("items",form.items.map((entry,itemIndex)=>itemIndex===index?event.target.value:entry))} required/><button type="button" onClick={()=>update("items",form.items.filter((_,itemIndex)=>itemIndex!==index))} disabled={form.items.length===1}><X size={14}/></button></div>)}<button type="button" className="secondary-button" onClick={()=>update("items",[...form.items,""])}><Plus size={14}/>Add item</button></div></section><footer><Link href="/celebrations" className="secondary-button">Cancel</Link><button className="primary-button" disabled={busy}>{busy?<LoaderCircle className="spin" size={16}/>:<Check size={16}/>} {busy?"Creating…":"Create celebration"}</button></footer></form></div></AppShell>;
}

function Field({label,value,set,type="text",required=false,wide=false}:{label:string;value:string;set:(value:string)=>void;type?:string;required?:boolean;wide?:boolean}){return <label className={wide?"wide":""}>{label}<input type={type} value={value} onChange={(event)=>set(event.target.value)} required={required} min={type==="number"?"0":undefined} step={type==="number"?"0.01":undefined}/></label>}
