"use client";

import { useCallback, useEffect, useState } from "react";
import Link from "next/link";
import { AppShell } from "@/components/app-shell";
import { AccessibleDialog } from "@/components/accessible-dialog";
import { formatLkr } from "@/lib/demo-data";
import { AlertCircle, ArrowUpRight, Check, CircleDollarSign, HandCoins, Landmark, LoaderCircle, ReceiptText, RefreshCw, X } from "lucide-react";

type MoneyOrder = { id: string; recipient: string; occasion: string; district: string; collected: number; costs: number; profit: number; status: string };
type MoneyPayload = { summary: { collected: number; costs: number; partnerOutstanding: number; profit: number }; orders: MoneyOrder[] };
const empty: MoneyPayload = { summary: { collected: 0, costs: 0, partnerOutstanding: 0, profit: 0 }, orders: [] };

export default function MoneyPage() {
  const [data, setData] = useState(empty); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [recording, setRecording] = useState(false); const [notice, setNotice] = useState("");
  const load = useCallback(async () => { setLoading(true); try { const response = await fetch("/api/money", { cache: "no-store" }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error || "The money room could not be loaded."); setData({ summary: payload.summary || empty.summary, orders: (payload.orders || []).map((order: Record<string, unknown>) => ({ id: String(order.id), recipient: String(order.recipient || "Recipient pending"), occasion: String(order.occasion || order.invoiceNumber || "Celebration"), district: String(order.district || ""), collected: Number(order.collected ?? order.paid ?? 0), costs: Number(order.costs ?? 0), profit: Number(order.profit ?? 0), status: String(order.status || "Details").replace(/^./, (letter) => letter.toUpperCase()) })) }); setError(""); } catch (caught) { setError(caught instanceof Error ? caught.message : "The money room could not be loaded."); } finally { setLoading(false); } }, []);
  useEffect(() => { const timer = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timer); }, [load]);
  return <AppShell><div className="page money-page"><header className="page-header"><div><span className="eyebrow">Money room</span><h1>Clear money, calm mind.</h1><p>Actual figures stay visibly separate until every delivery and expense is reconciled.</p></div><div className="detail-actions"><Link className="secondary-button" href="/billing"><ReceiptText size={16}/>Open billing</Link><button className="primary-button" onClick={() => setRecording(true)} disabled={!data.orders.length}>+ Record expense</button></div></header>
    {notice && <div className="operational-notice success"><Check size={17} /><span>{notice}</span><button onClick={() => setNotice("")}><X size={14} /></button></div>}{error && <div className="operational-notice error"><AlertCircle size={18} /><span>{error}</span><button onClick={() => void load()}><RefreshCw size={14} />Try again</button></div>}
    <section className="money-ribbon"><div className="money-ribbon-lead"><CircleDollarSign /><span><small>Studio pulse</small><strong>{formatLkr(data.summary.collected)}</strong><em>customer money collected</em></span></div><div><ReceiptText /><span><small>Recorded costs</small><strong>{formatLkr(data.summary.costs)}</strong><em>actual + estimated</em></span></div><div><Landmark /><span><small>Partner outstanding</small><strong>{formatLkr(data.summary.partnerOutstanding)}</strong><em>unsettled balances</em></span></div><div><HandCoins /><span><small>Distributable profit</small><strong>{formatLkr(data.summary.profit)}</strong><em>until reconciled</em></span></div></section>
    <div className="reconciliation-head"><div><span className="eyebrow">Order reconciliation</span><h2>Recent celebrations</h2></div><div><span><i className="actual" />Actual</span><span><i className="estimated" />Includes estimates</span></div></div>
    {loading ? <section className="directory-loading"><LoaderCircle className="spin" />Balancing the studio ledger…</section> : data.orders.length ? <section className="reconcile-table"><header><span>Celebration</span><span>Collected</span><span>Costs</span><span>Profit</span><span>Status</span><span /></header>{data.orders.map((order) => <article key={order.id}><div><strong>{order.recipient}</strong><small>{order.occasion} · {order.district}</small></div><span>{formatLkr(order.collected)}</span><span>{formatLkr(order.costs)}</span><strong className="profit-number">{formatLkr(order.profit)}</strong><span className={`reconcile-status ${order.status === "Reconciled" ? "done" : "estimate"}`}>{order.status === "Reconciled" ? <><Check size={12} />Reconciled</> : order.status}</span><Link href={`/celebrations/${order.id}`}><ArrowUpRight size={17} /></Link></article>)}</section> : !error && <div className="empty-state"><ReceiptText size={27} /><h3>No celebration ledger yet</h3><p>Payments and expenses will appear here after the first live celebration is created.</p></div>}
    <aside className="money-footnote"><div><span className="stamp">80<br /><small>20</small></span><p><strong>Profit shares are previews until reconciliation.</strong><br />Finalise only after delivery, partner balances, refunds and all actual costs are confirmed.</p></div></aside>
    {recording && <GlobalExpense orders={data.orders} close={() => setRecording(false)} saved={() => { setRecording(false); setNotice("Expense recorded in the celebration ledger."); void load(); }} />}
  </div></AppShell>;
}

function GlobalExpense({ orders, close, saved }: { orders: MoneyOrder[]; close: () => void; saved: () => void }) { const [orderId, setOrderId] = useState(orders[0]?.id || ""); const [description, setDescription] = useState(""); const [amount, setAmount] = useState(""); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); async function submit(event: React.FormEvent) { event.preventDefault(); setBusy(true); try { const response = await fetch(`/api/orders/${orderId}/expenses`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ description, amount: Number(amount) }) }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error || "Expense could not be recorded."); saved(); } catch (caught) { setError(caught instanceof Error ? caught.message : "Expense could not be recorded."); } finally { setBusy(false); } } return <AccessibleDialog labelId="expense-editor-title" className="partner-editor" onClose={close}><form onSubmit={(event) => void submit(event)}><header><div><small>Studio ledger</small><h2 id="expense-editor-title">Record expense</h2></div><button type="button" onClick={close} aria-label="Close editor"><X /></button></header>{error && <div className="operational-notice error"><AlertCircle size={17} />{error}</div>}<div className="partner-editor-fields"><label>Celebration<select value={orderId} onChange={(event) => setOrderId(event.target.value)}>{orders.map((order) => <option key={order.id} value={order.id}>{order.recipient} · {order.occasion}</option>)}</select></label><label>Description<input required value={description} onChange={(event) => setDescription(event.target.value)} /></label><label>Amount in LKR<input type="number" min="0.01" step="0.01" required value={amount} onChange={(event) => setAmount(event.target.value)} /></label></div><footer><button type="button" className="secondary-button" onClick={close}>Cancel</button><button className="primary-button" disabled={busy || !Number(amount)}>{busy ? <LoaderCircle className="spin" size={16} /> : <ReceiptText size={16} />}{busy ? "Saving…" : "Record expense"}</button></footer></form></AccessibleDialog>; }
