"use client";

import Link from "next/link";
import { useSearchParams } from "next/navigation";
import { Suspense, useCallback, useEffect, useMemo, useState } from "react";
import { AlertCircle, ArrowUpRight, Check, FilePlus2, FileText, Filter, LoaderCircle, RefreshCw, Search, X } from "lucide-react";
import { AccessibleDialog } from "@/components/accessible-dialog";
import { AppShell } from "@/components/app-shell";
import { Toast } from "@/components/ui";
import { formatLkr } from "@/lib/demo-data";

type DocumentType = "quote" | "proforma" | "invoice" | "receipt" | "credit_note";
type BillingDocument = { id: string; number: string; customerName: string; celebrationId?: string; celebration?: string; type: DocumentType; issueDate: string; dueDate?: string; total: number; paid: number; balance: number; status: string };
type Summary = { outstanding: number; collected: number; overdue: number; documentCount: number };
type CelebrationOption = { id: string; recipient: string; sender?: string; occasion?: string; total?: number; items?: Array<{ description?: string; quantity?: number; unitPrice?: number }> };
type LineItem = { description: string; quantity: number; unitPrice: number };

const emptySummary: Summary = { outstanding: 0, collected: 0, overdue: 0, documentCount: 0 };
const types: Array<{ value: DocumentType; label: string }> = [
  { value: "quote", label: "Quotation" }, { value: "proforma", label: "Proforma" }, { value: "invoice", label: "Invoice" },
  { value: "receipt", label: "Receipt" }, { value: "credit_note", label: "Credit note" },
];
const dateValue = (offset = 0) => { const date = new Date(); date.setDate(date.getDate() + offset); return date.toISOString().slice(0, 10); };
const money = (value: unknown) => Number(value || 0);

export default function BillingPage() { return <Suspense fallback={<AppShell><div className="page detail-state"><LoaderCircle className="spin"/><h1>Opening the billing desk…</h1></div></AppShell>}><BillingPageContent/></Suspense>; }

function BillingPageContent() {
  const searchParams = useSearchParams();
  const celebrationPrefill = searchParams.get("celebration") || "";
  const [documents, setDocuments] = useState<BillingDocument[]>([]); const [summary, setSummary] = useState(emptySummary);
  const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [query, setQuery] = useState("");
  const [status, setStatus] = useState("all"); const [type, setType] = useState("all"); const [creating, setCreating] = useState(Boolean(celebrationPrefill)); const [notice, setNotice] = useState("");
  const load = useCallback(async () => {
    setLoading(true); setError("");
    try { const response = await fetch("/api/invoices", { cache: "no-store" }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error || "The billing desk could not be opened.");
      const raw = payload.invoices || [];
      const mapped = raw.map((doc: Record<string, unknown>) => ({ id: String(doc.id), number: String(doc.document_number || "Draft"), customerName: String(doc.customer_name || "Customer pending"), celebrationId: doc.invoice_id ? String(doc.invoice_id) : undefined, celebration: "Celebration document", type: String(doc.document_type || "invoice") as DocumentType, issueDate: String(doc.issue_date || doc.created_at || ""), dueDate: doc.due_date ? String(doc.due_date) : undefined, total: money(doc.total), paid: money(doc.paid), balance: money(doc.total) - money(doc.paid), status: String(doc.status || "draft") }));
      setDocuments(mapped); setSummary(payload.summary || { outstanding: mapped.reduce((sum: number, doc: BillingDocument) => sum + doc.balance, 0), collected: mapped.reduce((sum: number, doc: BillingDocument) => sum + doc.paid, 0), overdue: mapped.filter((doc: BillingDocument) => doc.status === "overdue").reduce((sum: number, doc: BillingDocument) => sum + doc.balance, 0), documentCount: mapped.length });
    } catch (caught) { setError(caught instanceof Error ? caught.message : "The billing desk could not be opened."); } finally { setLoading(false); }
  }, []);
  useEffect(() => { const timer = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timer); }, [load]);
  const filtered = useMemo(() => documents.filter((doc) => (status === "all" || doc.status === status) && (type === "all" || doc.type === type) && `${doc.number} ${doc.customerName} ${doc.celebration}`.toLowerCase().includes(query.toLowerCase())), [documents, query, status, type]);
  return <AppShell><div className="page billing-page"><header className="page-header"><div><span className="eyebrow">Billing desk</span><h1>Every promise, on paper.</h1><p>Issue polished documents, track advances, and keep every remaining balance easy to see.</p></div><button className="primary-button" onClick={() => setCreating(true)}><FilePlus2 size={17}/>New document</button></header>
    {error && <div className="operational-notice error" role="alert"><AlertCircle size={18}/><span>{error}</span><button onClick={() => void load()}><RefreshCw size={14}/>Try again</button></div>}
    <section className="billing-ribbon" aria-label="Billing summary"><div className="billing-ribbon-lead"><span><small>Open balance</small><strong>{formatLkr(summary.outstanding)}</strong><em>still to collect</em></span></div><div><small>Collected</small><strong>{formatLkr(summary.collected)}</strong><em>verified payments</em></div><div className="attention"><small>Overdue</small><strong>{formatLkr(summary.overdue)}</strong><em>needs a follow-up</em></div><div><small>Documents</small><strong>{summary.documentCount}</strong><em>across all types</em></div></section>
    <section className="ledger-desk"><div className="billing-toolbar"><label className="search-field"><Search size={17}/><span className="sr-only">Search documents</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search number, customer or celebration"/></label><label><Filter size={15}/><span className="sr-only">Filter status</span><select value={status} onChange={(event) => setStatus(event.target.value)}><option value="all">All statuses</option>{["draft","issued","partial","paid","overdue","void","refunded"].map((value) => <option key={value} value={value}>{pretty(value)}</option>)}</select></label><label><span className="sr-only">Filter document type</span><select value={type} onChange={(event) => setType(event.target.value)}><option value="all">All document types</option>{types.map((entry) => <option key={entry.value} value={entry.value}>{entry.label}</option>)}</select></label><span>{filtered.length} shown</span></div>
      {loading ? <div className="directory-loading"><LoaderCircle className="spin"/>Opening the document ledger…</div> : filtered.length ? <div className="document-ledger" role="table" aria-label="Billing documents"><div className="document-ledger-head" role="row"><span>Document</span><span>Customer / celebration</span><span>Issued / due</span><span>Total</span><span>Paid / balance</span><span>Status</span><span/></div>{filtered.map((doc) => <article key={doc.id} role="row"><div data-label="Document"><strong>{doc.number}</strong><small>{typeLabel(doc.type)}</small></div><div data-label="Customer"><strong>{doc.customerName}</strong><small>{doc.celebration || "Standalone document"}</small></div><div data-label="Dates"><strong>{shortDate(doc.issueDate)}</strong><small>{doc.dueDate ? `Due ${shortDate(doc.dueDate)}` : "No due date"}</small></div><strong data-label="Total">{formatLkr(doc.total)}</strong><div data-label="Paid / balance"><strong>{formatLkr(doc.paid)}</strong><small>{formatLkr(doc.balance)} open</small></div><span data-label="Status" className={`billing-status ${doc.status}`}>{pretty(doc.status)}</span><Link href={`/billing/${doc.id}`} aria-label={`Open ${doc.number}`}><ArrowUpRight size={17}/></Link></article>)}</div> : !error && <div className="empty-state"><FileText size={29}/><h3>{documents.length ? "No documents match" : "Your first document starts here"}</h3><p>{documents.length ? "Clear a filter or try another customer name." : "Create a quotation, deposit request or invoice from a celebration."}</p><button className="primary-button" onClick={() => setCreating(true)}>Create document</button></div>}
    </section>{creating && <DocumentEditor celebrationPrefill={celebrationPrefill} close={() => setCreating(false)} saved={(message) => { setCreating(false); setNotice(message); void load(); }}/>} {notice && <Toast message={notice} onClose={() => setNotice("")}/>}</div></AppShell>;
}

function DocumentEditor({ celebrationPrefill, close, saved }: { celebrationPrefill: string; close: () => void; saved: (message: string) => void }) {
  const [celebrations, setCelebrations] = useState<CelebrationOption[]>([]);
  const [form, setForm] = useState({ celebrationId: celebrationPrefill, type: "invoice" as DocumentType, issueDate: dateValue(), dueDate: dateValue(7), paymentMode: "full", depositValue: "50", discount: "0", deliveryFee: "0", taxAmount: "0", terms: "" });
  const [items, setItems] = useState<LineItem[]>([{ description: "Celebration package", quantity: 1, unitPrice: 0 }]); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  useEffect(() => { Promise.all([fetch("/api/orders", { cache: "no-store" }), fetch("/api/settings/invoices", { cache: "no-store" })]).then(async ([ordersResponse, settingsResponse]) => { const orders = await ordersResponse.json(); const settings = await settingsResponse.json(); const mapped: CelebrationOption[] = (orders.orders || []).map((entry: Record<string, unknown>) => ({ id: String(entry.id), recipient: String(entry.recipient || "Recipient"), sender: String(entry.sender || ""), occasion: String(entry.occasion || "Celebration"), total: money(entry.total), items: Array.isArray(entry.itemDetails) ? entry.itemDetails : [] })); setCelebrations(mapped); const selected = mapped.find((entry) => entry.id === celebrationPrefill); if (selected) setItems(selected.items?.length ? selected.items.map((item) => ({ description: item.description || "Celebration item", quantity: money(item.quantity) || 1, unitPrice: money(item.unitPrice) })) : [{ description: `${selected.occasion || "Celebration"} for ${selected.recipient}`, quantity: 1, unitPrice: selected.total || 0 }]); setForm((current) => ({ ...current, terms: String(settings.default_terms || ""), depositValue: String(settings.default_deposit_percent ?? 50), dueDate: dateValue(Number(settings.default_due_days ?? 7)) })); }).catch(() => undefined); }, [celebrationPrefill]);
  function selectCelebration(celebrationId: string) { setForm({ ...form, celebrationId }); const selected = celebrations.find((entry) => entry.id === celebrationId); if (selected) setItems(selected.items?.length ? selected.items.map((item) => ({ description: item.description || "Celebration item", quantity: money(item.quantity) || 1, unitPrice: money(item.unitPrice) })) : [{ description: `${selected.occasion || "Celebration"} for ${selected.recipient}`, quantity: 1, unitPrice: selected.total || 0 }]); }
  const subtotal = items.reduce((sum, item) => sum + item.quantity * item.unitPrice, 0); const discount = money(form.discount); const tax = money(form.taxAmount); const total = subtotal - discount + money(form.deliveryFee) + tax; const requestedPaymentAmount = form.paymentMode === "deposit" ? total * money(form.depositValue) / 100 : total;
  async function submit(issue: boolean) { if (!form.celebrationId) { setError("Choose a celebration before creating a billing document."); return; } setBusy(true); setError(""); try { const response = await fetch(`/api/orders/${form.celebrationId}/invoices`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ documentType: form.type, currency: "LKR", issueDate: form.issueDate, dueDate: form.dueDate || undefined, requestedPaymentAmount, items: items.map((item) => ({ ...item, discount: 0, taxAmount: 0 })), discount, deliveryFee: money(form.deliveryFee), taxAmount: tax, terms: form.terms || undefined }) }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error || "The document could not be saved."); const documentId = payload.invoice?.document?.id; if (issue && documentId) { const issueResponse = await fetch(`/api/invoices/${documentId}/issue`, { method: "POST" }); const issuePayload = await issueResponse.json(); if (!issueResponse.ok) throw new Error(issuePayload.error || "The draft was saved but could not be issued."); } saved(issue ? "Document issued and added to the ledger." : "Draft saved to the document ledger."); } catch (caught) { setError(caught instanceof Error ? caught.message : "The document could not be saved."); } finally { setBusy(false); } }
  return <AccessibleDialog labelId="document-editor-title" className="billing-editor" onClose={close}><form onSubmit={(event) => { event.preventDefault(); void submit(false); }}><header><div><small>New customer document</small><h2 id="document-editor-title">Compose at the ribbon desk</h2></div><button type="button" onClick={close} aria-label="Close document editor"><X/></button></header><div className="billing-editor-scroll">{error && <div className="operational-notice error" role="alert"><AlertCircle size={17}/>{error}</div>}<section><h3>Document</h3><div className="editor-grid"><label>Celebration<select value={form.celebrationId} onChange={(event) => selectCelebration(event.target.value)}><option value="">Standalone document</option>{celebrations.map((entry) => <option key={entry.id} value={entry.id}>{entry.recipient} · {entry.occasion}</option>)}</select></label><label>Type<select value={form.type} onChange={(event) => setForm({ ...form, type: event.target.value as DocumentType })}>{types.map((entry) => <option key={entry.value} value={entry.value}>{entry.label}</option>)}</select></label><label>Issue date<input type="date" required value={form.issueDate} onChange={(event) => setForm({ ...form, issueDate: event.target.value })}/></label><label>Due date<input type="date" value={form.dueDate} onChange={(event) => setForm({ ...form, dueDate: event.target.value })}/></label></div></section>
      <section><div className="editor-section-head"><h3>Line items</h3><button type="button" onClick={() => setItems([...items, { description: "", quantity: 1, unitPrice: 0 }])}>+ Add line</button></div><div className="invoice-lines">{items.map((item, index) => <div key={index}><label>Description<input required value={item.description} onChange={(event) => setItems(items.map((entry, i) => i === index ? { ...entry, description: event.target.value } : entry))}/></label><label>Qty<input type="number" min="0.01" step="0.01" required value={item.quantity} onChange={(event) => setItems(items.map((entry, i) => i === index ? { ...entry, quantity: money(event.target.value) } : entry))}/></label><label>Unit price<input type="number" min="0" step="0.01" required value={item.unitPrice} onChange={(event) => setItems(items.map((entry, i) => i === index ? { ...entry, unitPrice: money(event.target.value) } : entry))}/></label><strong>{formatLkr(item.quantity * item.unitPrice)}</strong><button type="button" disabled={items.length === 1} onClick={() => setItems(items.filter((_, i) => i !== index))} aria-label="Remove line"><X size={14}/></button></div>)}</div></section>
      <section><h3>Amounts & terms</h3><div className="editor-grid"><label>Discount (LKR)<input type="number" min="0" value={form.discount} onChange={(event) => setForm({ ...form, discount: event.target.value })}/></label><label>Delivery fee (LKR)<input type="number" min="0" value={form.deliveryFee} onChange={(event) => setForm({ ...form, deliveryFee: event.target.value })}/></label><label>Tax amount (LKR)<input type="number" min="0" value={form.taxAmount} onChange={(event) => setForm({ ...form, taxAmount: event.target.value })}/></label><label>Amount requested<select value={form.paymentMode} onChange={(event) => setForm({ ...form, paymentMode: event.target.value })}><option value="full">Full balance</option><option value="deposit">Advance percentage</option></select></label>{form.paymentMode === "deposit" && <label>Advance percentage<input type="number" min="0" max="100" value={form.depositValue} onChange={(event) => setForm({ ...form, depositValue: event.target.value })}/></label>}<label className="wide">Terms & conditions<textarea rows={5} value={form.terms} onChange={(event) => setForm({ ...form, terms: event.target.value })}/></label></div></section><aside className="invoice-mini-preview"><span>{form.paymentMode === "deposit" ? "Advance requested" : "Document total"}</span><strong>{formatLkr(requestedPaymentAmount)}</strong><small>Total {formatLkr(total)} · tax {formatLkr(tax)} · discount {formatLkr(discount)}</small></aside></div><footer><button type="button" className="secondary-button" onClick={close}>Cancel</button><button className="secondary-button" disabled={busy}>{busy ? "Saving…" : "Save draft"}</button><button type="button" className="primary-button" disabled={busy || !form.celebrationId || !items.every((item) => item.description && item.quantity > 0)} onClick={() => void submit(true)}>{busy ? <LoaderCircle className="spin" size={16}/> : <Check size={16}/>}Issue document</button></footer></form></AccessibleDialog>;
}

function pretty(value: string) { return value.replaceAll("_", " ").replace(/\b\w/g, (letter) => letter.toUpperCase()); }
function typeLabel(value: DocumentType) { return types.find((entry) => entry.value === value)?.label || pretty(value); }
function shortDate(value?: string) { if (!value) return "—"; const date = new Date(`${value.slice(0, 10)}T00:00:00`); return Number.isNaN(date.valueOf()) ? value : new Intl.DateTimeFormat("en-LK", { day: "2-digit", month: "short", year: "numeric" }).format(date); }
