"use client";

import { useCallback, useEffect, useState } from "react";
import { AppShell } from "@/components/app-shell";
import { AccessibleDialog } from "@/components/accessible-dialog";
import { formatLkr } from "@/lib/demo-data";
import type { Partner } from "@/lib/types";
import { AlertCircle, ArrowUpRight, LoaderCircle, MapPin, Plus, RefreshCw, Star, WalletCards, X } from "lucide-react";

export default function PartnersPage() {
  const [partners, setPartners] = useState<Partner[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [notice, setNotice] = useState(""); const [adding, setAdding] = useState(false);
  const load = useCallback(async () => { setLoading(true); try { const response = await fetch("/api/partners", { cache: "no-store" }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error || "Partner circle could not be loaded."); setPartners(payload.partners || []); setError(""); } catch (caught) { setError(caught instanceof Error ? caught.message : "Partner circle could not be loaded."); } finally { setLoading(false); } }, []);
  useEffect(() => { const timer = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timer); }, [load]);
  return <AppShell><div className="page partners-page"><header className="page-header"><div><span className="eyebrow">Trusted hands</span><h1>Our partner circle.</h1><p>Who can help, where they work, and what is still owed—all from live studio records.</p></div><button className="primary-button" onClick={() => setAdding(true)}><Plus size={18} />Add partner</button></header>
    {notice && <div className="operational-notice success" role="status"><span>{notice}</span><button onClick={() => setNotice("")}><X size={14} /></button></div>}
    {error && <div className="operational-notice error" role="alert"><AlertCircle size={18} /><span>{error}</span><button onClick={() => void load()}><RefreshCw size={14} />Try again</button></div>}
    <div className="section-title"><h2>Partner directory</h2><span className="attention-count">{partners.length} active partners</span></div>
    {loading ? <section className="directory-loading"><LoaderCircle className="spin" />Opening the partner ledger…</section> : partners.length ? <section className="partner-directory">{partners.map((partner, index) => <article key={partner.id}><div className="partner-tag"><span>{partner.name.split(" ").map((word) => word[0]).join("").slice(0, 3)}</span><i>{String(index + 1).padStart(2, "0")}</i></div><h2>{partner.name}</h2><p className="partner-location"><MapPin size={14} />{partner.location || "Service area not set"}</p><div className="service-tags">{partner.services.length ? partner.services.map((service) => <span key={service}>{service}</span>) : <span>Services need adding</span>}</div><dl><div><dt><Star size={14} />Reliability</dt><dd>{partner.reliability}%</dd></div><div><dt>Open orders</dt><dd>{partner.openOrders}</dd></div><div><dt><WalletCards size={14} />Balance due</dt><dd>{formatLkr(partner.balance)}</dd></div></dl><div className="partner-response"><small>Latest</small><strong>{partner.response || "No recent activity"}</strong></div><footer><span>Live partner record</span><ArrowUpRight size={17} /></footer></article>)}</section> : !error && <div className="empty-state"><Plus size={26} /><h3>Build your trusted circle</h3><p>Add the first cake maker, florist or delivery partner to assign them to celebrations.</p><button className="primary-button" onClick={() => setAdding(true)}>Add first partner</button></div>}
    {adding && <PartnerForm close={() => setAdding(false)} saved={(message) => { setAdding(false); setNotice(message); void load(); }} />}
  </div></AppShell>;
}

function PartnerForm({ close, saved }: { close: () => void; saved: (message: string) => void }) {
  const [form, setForm] = useState({ name: "", location: "", services: "", phone: "" }); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  async function submit(event: React.FormEvent) { event.preventDefault(); setBusy(true); setError(""); try { const response = await fetch("/api/partners", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name: form.name, phone: form.phone || null, address: null, services: form.services.split(",").map((value) => value.trim()).filter(Boolean), serviceAreas: [form.location], reliability: 100 }) }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error || "Partner could not be added."); saved(`${form.name} was added to the partner circle.`); } catch (caught) { setError(caught instanceof Error ? caught.message : "Partner could not be added."); } finally { setBusy(false); } }
  return <AccessibleDialog labelId="partner-editor-title" className="partner-editor" onClose={close}><form onSubmit={(event) => void submit(event)}><header><div><small>Trusted hands</small><h2 id="partner-editor-title">Add a partner</h2></div><button type="button" onClick={close} aria-label="Close editor"><X /></button></header>{error && <div className="operational-notice error"><AlertCircle size={17} />{error}</div>}<div className="partner-editor-fields"><label>Partner name<input required value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} /></label><label>Service area<input required value={form.location} onChange={(event) => setForm({ ...form, location: event.target.value })} placeholder="Colombo, Kandy…" /></label><label>WhatsApp phone<input type="tel" value={form.phone} onChange={(event) => setForm({ ...form, phone: event.target.value })} /></label><label>Services<input value={form.services} onChange={(event) => setForm({ ...form, services: event.target.value })} placeholder="Cake, flowers, delivery" /></label></div><footer><button type="button" className="secondary-button" onClick={close}>Cancel</button><button className="primary-button" disabled={busy}>{busy ? <LoaderCircle className="spin" size={16} /> : <Plus size={16} />}{busy ? "Adding…" : "Add partner"}</button></footer></form></AccessibleDialog>;
}
